server:
  port: ${server.port}
spring:
  application:
    name: ${server.name}
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${cloud.db.host}:${cloud.db.port}/${cloud.db.name}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${cloud.db.user}
    password: ${cloud.db.pw}
  cloud:
    nacos:
      server-addr: ${cloud.nacos.host}:${cloud.nacos.port}
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.cloud: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: ${openapi.title}
    description: ${openapi.description}
    email: ${openapi.email}
    concat: ${openapi.concat}
    version: ${openapi.version}
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.cloud.user.controller
cloud:
  jwt:
    location: classpath:cloud.jks
    alias: cloudall
    password: cloud
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi